# Generated by Django 2.1.7 on 2019-03-25 17:36

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GolfTracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=1000)),
                ('datePlayed', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_number', models.CharField(choices=[('1', 'Hole 1'), ('2', 'Hole 2'), ('3', 'Hole 3'), ('4', 'Hole 4'), ('5', 'Hole 5'), ('6', 'Hole 6'), ('7', 'Hole 7')], max_length=1)),
                ('start_time', models.DateTimeField()),
                ('stop_time', models.DateTimeField()),
                ('geo_codes', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=6, max_digits=9), size=None), size=None)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GolfTracker.Game')),
            ],
        ),
    ]
