# Generated by Django 2.1.7 on 2019-03-25 18:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GolfTracker', '0002_game_hole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hole',
            name='geo_codes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=6, max_digits=9), size=None),
        ),
    ]
