# Generated by Django 2.1.7 on 2019-04-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GolfTracker', '0006_auto_20190331_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='hole',
            name='distance_yards',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
            preserve_default=False,
        ),
    ]
